# Autogenerated wrapper script for BWA_jll for x86_64-apple-darwin
export bwa, libbwa

using Zlib_jll
JLLWrappers.@generate_wrapper_header("BWA")
JLLWrappers.@declare_executable_product(bwa)
JLLWrappers.@declare_library_product(libbwa, "@rpath/libbwa.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_executable_product(
        bwa,
        "bin/bwa",
    )

    JLLWrappers.@init_library_product(
        libbwa,
        "lib/libbwa.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
